baseURL = "https://blog.troy-y.org/"
title = "Troy's Blog"
theme = "PaperMod"
paginate = 20
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  description = "Troy Mitchell's blog on Linux kernel, embedded systems, RISC-V, and open-source development."
  keywords = ["Linux kernel", "embedded systems", "RISC-V", "operating systems", "open-source", "HPC"]
  author = "Troy Mitchell"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      comments = true
      defaultTheme = "auto"
      ShowReadingTime = true
      ShowShareButtons = false
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowToc = true
    [languages.en.params.homeInfoParams]
      Title = "Hey there 👋"
      Content = "I'm [Troy Mitchell](https://troy-y.org). Welcome to my blog.\n\n`GPG: 3FE5 535C F1B0 E658 E57D B59B AE1C 2FBE A7DB 42E1`"
    [[languages.en.params.socialIcons]]
      name = "github"
      url = "https://github.com/TroyMitchell911"
    [[languages.en.params.socialIcons]]
      name = "email"
      url = "mailto:i@troy-y.org"
    [[languages.en.params.socialIcons]]
      name = "rss"
      url = "/index.xml"
    [[languages.en.menu.main]]
      identifier = "archives"
      name = "Archives"
      url = "/archives/"
      weight = 5
    [[languages.en.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 15

  [languages.zh]
    languageName = "中文"
    weight = 2
    languageCode = "zh-CN"
    [languages.zh.params]
      comments = true
      defaultTheme = "auto"
      ShowReadingTime = true
      ShowShareButtons = false
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowToc = true
    [languages.zh.params.homeInfoParams]
      Title = "你好 👋"
      Content = "我是 [Troy Mitchell](https://troy-y.org)。欢迎来到我的博客。\n\n`GPG: 3FE5 535C F1B0 E658 E57D B59B AE1C 2FBE A7DB 42E1`"
    [[languages.zh.params.socialIcons]]
      name = "github"
      url = "https://github.com/TroyMitchell911"
    [[languages.zh.params.socialIcons]]
      name = "email"
      url = "mailto:i@troy-y.org"
    [[languages.zh.params.socialIcons]]
      name = "rss"
      url = "/zh/index.xml"
    [[languages.zh.menu.main]]
      identifier = "archives"
      name = "归档"
      url = "/zh/archives/"
      weight = 5
    [[languages.zh.menu.main]]
      identifier = "tags"
      name = "标签"
      url = "/zh/tags/"
      weight = 10
    [[languages.zh.menu.main]]
      identifier = "search"
      name = "搜索"
      url = "/zh/search/"
      weight = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  style = "dracula"
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  tabWidth = 8
